spring:
  application:
    name: hmdp-web-aiops-demo
  datasource:
    url: ${AIOPS_DEMO_MYSQL_URL:jdbc:mysql://127.0.0.1:13307/hmdp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${AIOPS_DEMO_MYSQL_USERNAME:root}
    password: ${AIOPS_DEMO_MYSQL_ROOT_PASSWORD:123456}
  redis:
    host: 127.0.0.1
    port: ${AIOPS_DEMO_REDIS_PORT:16379}
  kafka:
    bootstrap-servers: ${AIOPS_DEMO_KAFKA_BOOTSTRAP_SERVERS:127.0.0.1:29092}
    consumer:
      group-id: hmdp-aiops-mysql-demo-consumer-v1

canal:
  enabled: false

seckill:
  message:
    mode: kafka

hmdp:
  aiops:
    business-metrics:
      enabled: true
      role: hmdp-web
      port: ${AIOPS_DEMO_WEB_METRICS_PORT:18081}
  kafka:
    listener:
      enabled: false
    topics:
      voucher-order: hmdp.aiops.mysql-demo.order.main.v1
      voucher-order-retry: hmdp.aiops.mysql-demo.order.retry.v1
      voucher-order-dlt: hmdp.aiops.mysql-demo.order.dlt.v1
    consumer:
      retry-group-id: hmdp-aiops-mysql-demo-retry-v1
      dlt-group-id: hmdp-aiops-mysql-demo-dlt-v1
  seckill:
    redis-stream-consumer:
      enabled: false
